type TestCase = {
	description: string;
	expected: boolean;
	test: string;
};

export const TEST_CASES: TestCase[] = [
	{
		description: 'empty field',
		expected: false,
		test: `
			..........
			..........
			..........
			..........
			..........
			..........
			..........
			..........
			..........
			..........
		`
	},
	{
		description: 'completed line',
		expected: true,
		test: `
			..........
			..........
			..........
			..........
			..........
			..........
			..........
			..........
			..........
			.....@@@@@
		`
	},
	{
		description: 'completed row',
		expected: true,
		test: `
			1.........
			1.........
			1.........
			1.........
			1.........
			..........
			..........
			..........
			..........
			..........
		`
	},
	{
		description: 'completed diagonal (up)',
		expected: true,
		test: `
			..........
			..........
			..........
			......$...
			.....$....
			....$.....
			...$......
			..$.......
			..........
			..........
		`
	},
	{
		description: 'completed diagonal (down)',
		expected: true,
		test: `
			..........
			..........
			.....^....
			......^...
			.......^..
			........^.
			.........^
			..........
			..........
			..........
		`
	},
	{
		description: 'almost completed lines',
		expected: false,
		test: `
			..........
			..........
			..........
			..........
			..........
			..........
			..........
			2222.2222.
			3.3333.333
			..........
		`
	},
	{
		description: 'almost completed rows',
		expected: false,
		test: `
			2.........
			23........
			.3........
			23........
			23........
			2.........
			23........
			.3........
			23........
			23........
		`
	},
	{
		description: 'almost completed diagonal (up)',
		expected: false,
		test: `
			........2.
			.......23.
			......23..
			.....23...
			.....3....
			...2......
			..23......
			.23.......
			23........
			3.........
		`
	},
	{
		description: 'almost completed diagonal (down)',
		expected: false,
		test: `
			3.........
			23........
			.23.......
			..23......
			...2......
			.....3....
			.....23...
			......23..
			.......23.
			........2.
		`
	},
	{
		description: 'almost completed lines, rows, diagonals',
		expected: false,
		test: `
			xxxx......
			......oooo
			o.........
			o......xo.
			o.....xo..
			o....xo...
			.xo.xo...x
			..xo.....x
			...xo....x
			....xo...x
		`
	},
	{
		description: 'completed line, but different colors',
		expected: false,
		test: `
			..........
			..........
			11112222..
			..........
			..........
			..........
			..........
			..........
			..........
			..........
		`
	},
	{
		description: 'completed row, but different colors',
		expected: false,
		test: `
			..........
			.......1..
			.......1..
			.......1..
			.......1..
			.......2..
			.......2..
			.......2..
			.......2..
			..........
		`
	},
	{
		description: 'completed diagonal (up), but different colors',
		expected: false,
		test: `
			..........
			.......1..
			......1...
			.....1....
			....1.....
			...2......
			..2.......
			.2........
			2.........
			..........
		`
	},
	{
		description: 'completed diagonal (down), but different colors',
		expected: false,
		test: `
			..........
			1.........
			.1........
			..1.......
			...1......
			....2.....
			.....2....
			......2...
			.......2..
			..........
		`
	},
	{
		description: 'completed broken line (angle)',
		expected: false,
		test: `
			..........
			..........
			.3333.....
			.3........
			.3........
			..........
			..........
			..........
			..........
			..........
		`
	},
	{
		description: 'completed broken line (square)',
		expected: false,
		test: `
			..........
			..........
			.3333.....
			.3..3.....
			.3333.....
			..........
			..........
			..........
			..........
			..........
		`
	},
	{
		description: 'completed broken line (empty square)',
		expected: false,
		test: `
			..........
			..........
			.****.....
			.*..*.....
			.*..*.....
			.****.....
			..........
			..........
			..........
			..........
		`
	},
	{
		description: 'completed broken line (filled square)',
		expected: false,
		test: `
			..........
			..........
			.****.....
			.****.....
			.****.....
			.****.....
			..........
			..........
			..........
			..........
		`
	},
	{
		description: 'completed broken line (snake)',
		expected: false,
		test: `
			..........
			..........
			..........
			..........
			..........
			....s.s.s.
			.....s.s..
			..........
			..........
			..........
		`
	},
	{
		description: 'from game on 2023/08/08',
		expected: false,
		test: `
			........x.
			....g..ggx
			..g..rrrgx
			...rgrrgg.
			...grrgrrg
			...grg..g.
			...gr.....
			..........
			..........
			..........
		`
	}
];
